# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brr < Formula
  desc "A delightful TUI speedtest with bufferbloat grading"
  homepage "https://github.com/allenan/brr"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/allenan/brr/releases/download/v1.0.0/brr_darwin_amd64.tar.gz"
      sha256 "fbee5706a57000de91eb7cf07875ca2853dfc914e230d17f782e462828fcfff6"

      def install
        bin.install "brr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/allenan/brr/releases/download/v1.0.0/brr_darwin_arm64.tar.gz"
      sha256 "bd67c402daf44d6af9e89e7aa4eb3fe77c49b9b197238db914839bb744b9816c"

      def install
        bin.install "brr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/allenan/brr/releases/download/v1.0.0/brr_linux_amd64.tar.gz"
      sha256 "da2b21df35fa72efa0c27496454f6bc03da3b775732fde2828b57116abfdb5cf"
      def install
        bin.install "brr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/allenan/brr/releases/download/v1.0.0/brr_linux_arm64.tar.gz"
      sha256 "a887a024745578a113cfa007145928db70582c43c899e57b14bbe8f2d6db7079"
      def install
        bin.install "brr"
      end
    end
  end
end
