# This file was generated by GoReleaser. DO NOT EDIT.
cask "brr" do
  name "brr"
  desc "A delightful TUI speedtest with bufferbloat grading"
  homepage "https://github.com/allenan/brr"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brr"

  on_macos do
    on_intel do
      url "https://github.com/allenan/brr/releases/download/v#{version}/brr_darwin_amd64.tar.gz"
      sha256 "f0707f7b7df9ed7e76d987459460c87f0b533c7d6f9ebacf3fc4776d754effbf"
    end
    on_arm do
      url "https://github.com/allenan/brr/releases/download/v#{version}/brr_darwin_arm64.tar.gz"
      sha256 "af62d6a08a648f27b62cff2ed4e68a925339a32706056c8da9468eba04948063"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/allenan/brr/releases/download/v#{version}/brr_linux_amd64.tar.gz"
      sha256 "60b874ec9249c41ba4e80c7dab3b9cb69e69854cfbcdbd31b7a3555143bf0114"
    end
    on_arm do
      url "https://github.com/allenan/brr/releases/download/v#{version}/brr_linux_arm64.tar.gz"
      sha256 "1d833e6adad6b1d3aff97c51ae1809a2a48d14b57070f26499350e8a436aaab0"
    end
  end

  # No zap stanza required
end
