# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herd < Formula
  desc "TUI manager for multiple Claude Code sessions"
  homepage "https://github.com/allenan/herd"
  version "0.1.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/allenan/herd/releases/download/v0.1.0/herd_0.1.0_darwin_amd64.tar.gz"
      sha256 "0084a28eb3dc29f8aab9830ea23dc6e401af76d8172ff418419d322b0540b7ac"

      def install
        bin.install "herd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/allenan/herd/releases/download/v0.1.0/herd_0.1.0_darwin_arm64.tar.gz"
      sha256 "5b3969228be915ce427992c7fecab4862759e4f3ab4afbc31cd2735427fea047"

      def install
        bin.install "herd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/allenan/herd/releases/download/v0.1.0/herd_0.1.0_linux_amd64.tar.gz"
      sha256 "70f5bb261f340a4e225d03a263c436f3e8c6172a302c88f526aae2f56a54f3ab"
      def install
        bin.install "herd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/allenan/herd/releases/download/v0.1.0/herd_0.1.0_linux_arm64.tar.gz"
      sha256 "1b71dfa43f30f86e076ddd2011e3eef36935cccef64f9844f485ee6d80606b32"
      def install
        bin.install "herd"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/herd --version")
  end
end
