# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herd < Formula
  desc "TUI manager for multiple Claude Code sessions"
  homepage "https://github.com/allenan/herd"
  version "0.3.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/allenan/herd/releases/download/v0.3.0/herd_0.3.0_darwin_amd64.tar.gz"
      sha256 "b1503a151990bb8911c38d9df00c4e5221e0120bfadd0d3b1f791078a455ee0f"

      def install
        bin.install "herd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/allenan/herd/releases/download/v0.3.0/herd_0.3.0_darwin_arm64.tar.gz"
      sha256 "a899f040017a7ec6a98c50ef960ce19c8f07d2742db51cd4a8655a92c6a83ca2"

      def install
        bin.install "herd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/allenan/herd/releases/download/v0.3.0/herd_0.3.0_linux_amd64.tar.gz"
      sha256 "80debacc98fc9fafdd9ed843f49b3c840764ee9310ab69e46989aacbe2a45c0c"
      def install
        bin.install "herd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/allenan/herd/releases/download/v0.3.0/herd_0.3.0_linux_arm64.tar.gz"
      sha256 "fd146e7c28cc11208f16100ab1b75924a8d4bce7820210b1ff1c85aa2ad9fe10"
      def install
        bin.install "herd"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/herd --version")
  end
end
